### PR TITLE
Run in SAP Business Technology Platform - Cloud Foundry environment

### PR DESCRIPTION
**Pull request by gregorwolf**

### CODE REVIEW

**Comment by larshp** [comment]
few thoughts:
a: the table maintenance itself will always be part of a larger application, so the CF deploy is just an example, which might become generic for more future open-abap projects
b: is it possible to move the CF stuff to a new folder `/cf/` ?
c: how to test the deployment via github actions? is it possible to spin up a CF environment, deploy to that, and check via `curl` that the application is running?

**Comment by gregorwolf** [comment]
a) OK
b) I've moved the mta.yaml to cf/. 
c) when CF credentials are provided yes. Will give it a try.

**Comment by larshp** [comment]
c: is it possible to spin up a CF environment in github actions, just without credentials?

**Comment by gregorwolf** [comment]
I've found [cf-mini](https://github.com/tchughesiv/cf-mini) but that didn't start. So my approach now would be to build the MTAR, extract its content and then run it. That is a bit like the CF buildpack does it. What do you think?

**Comment by larshp** [comment]
I think CF should help the ecosystem more to test stuff

anyhow, merging, thanks 👍

**Pull request merged**
